services:
    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongo-db:/data/db

    frontend:
      image: complaintraisesupportsystem-frontend
      container_name: frontend
      ports:
        - "5173:5173"

      depends_on:
        - backend

    backend:
      image: complaintraisesupportsystem-backend
      container_name: backend
      ports:
        - "2234:2234"
      depends_on:
        - mongodb

      environment:
        MONGO_URI: ${MONGO_URL}    


volumes:
  mongo-db:
